### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by vhikd** [libsndfile/libsndfile#45]
When I try to build on MacOS 10.8.4,it turns out this error message.

cc1plus: warning: command line option "-Wmissing-declarations" is valid for C/ObjC but not for C++
  CXXLD    sndfilehandle
ld: warning: ignoring file ../src/.libs/libsndfile.dylib, file was built for unsupported file format ( 0xce 0xfa 0xed 0xfe 0x c 0x 0 0x 0 0x 0 0x 9 0x 0 0x 0 0x 0 0x 6 0x 0 0x 0 0x 0 ) which is not the architecture being linked (x86_64): ../src/.libs/libsndfile.dylib
Undefined symbols for architecture x86_64:
  "_sf_close", referenced from:
      _main in sndfilehandle.o
  "_sf_open", referenced from:
      _main in sndfilehandle.o
  "_sf_read_short", referenced from:
      _main in sndfilehandle.o
  "_sf_write_short", referenced from:
      _main in sndfilehandle.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
make[1]: **\* [sndfilehandle] Error 1
make: **\* [all-recursive] Error 1

**Comment by amruthanad** [comment]
Hi!

I have the same issue. It cropped up all of a sudden. The same program I am trying to build now has been compiled/run before. My OS has been updated to Yosemite 10.10.

I tried fixing the issue both ways. I have linked the library in Xcode using the correct header search path. I made a fresh installation of libsndfile. It still doesn't fix the issue. I can provide any additional details necessary. 

Context: I am trying to compile a program, that reads a wave file and prints info.
OS:Mac OS X Yosemite 10.10


Undefined symbols for architecture i386:
  "_sf_close", referenced from:
      SndfileHandle::SNDFILE_ref::~SNDFILE_ref() in main.o
  "_sf_open", referenced from:
      SndfileHandle::SndfileHandle(char const*, int, int, int, int) in main.o
  "_sf_strerror", referenced from:
      SndfileHandle::strError() const in main.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The id was ld: symbol(s) not found for architecture x86_64 initially. I changed the architecture it was building against in Xcode and hence the new error id shows i386.

Could you help me fix this issue? Been struggling with it for a long time.

**Comment by erikd** [comment]
@amruthanad You have given me error message but not the compile comand that produced this error. On your machine:

a) What command are you using to compile?
b) Where is libsndfile installed?
c) Is it installed binary the same architecture (ir x86_64 vs i386).

**Comment by amruthanad** [comment]
a) I tried building it in Xcode as a part of a project. I could compile it from the command line using g++. What worked was: g++ -I/usr/local/include -lsndfile -o testwav testwav.c
When I try to build it as a project I get the aforementioned errors(in Xcode).

b) Libsndfile is installed in /usr/local/include directory.

c) I installed it exactly as described in README.md. I am new to using macOSX and also new to command line. I am not sure if its installed in the same architecture. Is there different install instructions for different architectures? (I have a macbook pro if that helps)

**Comment by erikd** [comment]
If you are building it with Xcode I can't help you. I do all my development on Linux and do not have any access to Mac OS.

However, you problem has nothing specifically to do with libsndfile and *everything* to do with Xcode. I suggest you seek Xcode help elesewhere.

**Comment by amruthanad** [comment]
Thank you for your response. I figured that must be the case as it compiles just fine with g++. Maybe I will just stick to command line compilation.

**Comment by hasanfaizal** [comment]
Hi I do have the same problem and I am using the Eclipse to compile the project,

$ gcc -lssl -lcrypto -o /Users/KHF/Documents/Eclipse/workspace/Test\ EC/EC.c 
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by amruthanad** [comment]
Hey! Make sure you compile it as a library and link the library when you
compile the code you have written. I was using Xcode. I had to compile
libsndfile as a library (xcode project built) and then link it. I am not
sure how to do it in Eclipse but there must be some way.

**Comment by erikd** [comment]
@hasanfaizal From what I can see, it seems your problem has nothing to do with libsndfile and everything to do with Eclipse. Since I have never used Eclipse, you are much better off asking for help elsewhere. Sorry I can't be of more help.
